- name: Setup tailscale
  hosts: all
  become: true

  roles:
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ vault_tailscale_authkey }}"
        tailscale_args: "--hostname={{ tailscale_hostname }}"

  tasks:
    - name: Allow traffic on tailscale0 interface
      ufw:
        rule: allow
        interface: tailscale0
        direction: in
