---
- name: Reload SSH
  ansible.builtin.service:
    name: ssh
    state: reloaded

- name: Reload ufw
  ansible.builtin.service:
    name: ufw
    state: reloaded

- name: Restart postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: restarted

- name: Recreate container
  community.docker.docker_compose_v2:
    project_src: "/opt/{{ project_name }}"
    state: present
    recreate: always
