project_url: staging.edenflowers.fi
maintenance_mode: false
tailscale_hostname: edenflowers-staging
papra_base_url: "https://papra-staging.edenflowers.fi"
imgproxy_prefix: https://images-staging.edenflowers.fi
image_tag: staging
db_name: "{{ project_name }}_staging"
