- name: Harden server
  hosts: all
  become: true
  remote_user: "{{ user }}"
  handlers:
    - name: Reload ufw
      service:
        name: ufw
        state: reloaded

    - name: Reload SSH
      service:
        name: ssh
        state: reloaded

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Disable PasswordAuthentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?\s*PasswordAuthentication\s'
        line: "PasswordAuthentication no"
        state: present
        backup: yes
      notify: Reload SSH

    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?\s*PermitRootLogin\s'
        line: "PermitRootLogin no"
        state: present
      notify: Reload SSH

    - name: Install Fail2Ban
      apt:
        name: fail2ban
        state: present

    - name: Start and enable Fail2Ban
      service:
        name: fail2ban
        state: started
        enabled: true

    - name: Install ufw
      apt:
        name: ufw
        state: present

    - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH

    - name: Enable ufw
      ufw:
        state: enabled
        policy: deny
        direction: incoming

