- name: Update packages
  hosts: all
  become: true
  remote_user: "{{ user }}"

  tasks:
    - name: Update all packages
      apt:
        upgrade: dist
        update_cache: yes

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      reboot:
        reboot_timeout: 300
      when: reboot_required.stat.exists
